name: Audit

on:
  push:
    # branches: [main]
  # pull_request:
    # branches: [main]

concurrency: 
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-test:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - name: Verify dependencies
      run: go mod verify

    - name: Build
      run: go build -v ./...

    - name: Run go vet (main)
      run: go vet ./...

    - name: Run go vet (inkcallerlib)
      run: cd inkcallerlib; go vet ./...

    - name: Run tests (main)
      run: go test -race -vet=off ./...

    - name: Run tests (inkcallerlib)
      run: cd inkcallerlib;go test -race -vet=off ./...
  audit:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - name: Verify dependencies
      run: go mod verify

    - name: Install staticcheck
      run: go install honnef.co/go/tools/cmd/staticcheck@latest

    - name: Run staticcheck (main)
      run: staticcheck ./...

    - name: Run staticcheck (inkcallerlib)
      run: cd inkcallerlib;staticcheck ./...

    - name: Install golint
      run: go install golang.org/x/lint/golint@latest

    - name: Run golint (main)
      run: golint ./...

    - name: Run golint (inkcallerlib)
      run: cd inkcallerlib;golint ./...
