name: Run

on: push

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.23

    - name: Build (main)
      run: go build -v ./...

    - name: Build (inkcallerlib)
      run: cd inkcallerlib; go build -v ./...

    - name: Run go vet (main)
      run: go vet ./...

    - name: Run go vet (inkcallerlib)
      run: cd inkcallerlib; go vet ./...

    - name: Run tests (main)
      run: go test -race -vet=off ./...

    - name: Run tests (inkcallerlib)
      run: cd inkcallerlib; go test -race -vet=off ./...

    ## TODO not working: 
    ## err:`missing ziphash: open hash: no such file or directory`
    ## `go clean --modcache` won't fix it 
    # - name: Verify dependencies
    #   run: go mod verify

    ## TODO not working:
    ## err:`-: cannot import "internal/cpu" (unknown iexport format version 2), export data is newer version - update tool (compile)`
    ## `go install golang.org/x/tools/...@latest` won't fix it 
    # - name: Install staticcheck
    #   run: go install honnef.co/go/tools/cmd/staticcheck@latest

    # - name: Run staticcheck (main)
    #   run: staticcheck ./...

    # - name: Run staticcheck (inkcallerlib)
    #   run: cd inkcallerlib;staticcheck ./...

    - name: Install golint
      run: go install golang.org/x/lint/golint@latest

    - name: Run golint (main)
      run: golint ./... | grep -v "should have comment or be unexported" | grep -v "which can be annoying to use" || true

    - name: Run golint (inkcallerlib)
      run: cd inkcallerlib; golint ./... | grep -v "should have comment or be unexported" | grep -v "which can be annoying to use" || true
